services:
  - type: web
    name: employee-attendance-backend
    env: node
    plan: free
    buildCommand: bash scripts/deploy.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: attendance-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://alfa-salaray-app.vercel.app
      - key: BCRYPT_ROUNDS
        value: 12
      - key: RATE_LIMIT_WINDOW_MS
        value: 60000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 1000

databases:
  - name: attendance-db
    plan: free
