services:
  - type: web
    name: employee-attendance-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: attendance-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://your-frontend-url.onrender.com

databases:
  - name: attendance-db
    plan: free
